spring:
  profiles:
    active: local

  jwt:
    secret: secretKey

  datasource:
    url: jdbc:mysql://localhost:3306/fashionDB
    username: fashion
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  logging.level:
    org.hibernate.SQL: debug